name: desafio_estante_de_livros
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Modular
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # General
  equatable: ^2.0.5
  intl: ^0.18.0
  asuka: ^2.0.2
  vocsy_epub_viewer: ^2.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #General
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.0+4

  #Tests
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg